In [1]:
from google.colab import drive

In [2]:
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [3]:
#importation des differents modules 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
#1-recuperation du dataset Coeur
data = pd.read_excel(r'/content/gdrive/My Drive/Coeur.xlsx')

In [5]:
#2-copie de data dans df 
df = data.copy()


In [6]:
#3- Verifier s'il y a des doublons et les supprimer
df.duplicated().sum()
df.drop_duplicates()

AGE   SEXE  TDT  PAR  ...  ANGINE  DEPRESSION       PENTE  CŒUR
0     40  homme   AA  140  ...     Non          0.0  Ascendant     0
1     49  femme  DNA  160  ...     Non          1.0       Plat     1
2     37  homme   AA  130  ...     Non          0.0  Ascendant     0
3     48  femme  ASY  138  ...     Oui          1.5       Plat     1
4     54  homme  DNA  150  ...     Non          0.0  Ascendant     0
..   ...    ...  ...  ...  ...     ...          ...        ...   ...
913   45  homme   AT  110  ...     Non          1.2       Plat     1
914   68  homme  ASY  144  ...     Non          3.4       Plat     1
915   57  homme  ASY  130  ...     Oui          1.2       Plat     1
916   57  femme   AA  130  ...     Non          0.0       Plat     1
917   38  homme  DNA  138  ...     Non          0.0  Ascendant     0

[918 rows x 12 columns]

In [18]:
#4- Verifier s'il existe des variables constante(variable avec une seule modalité)
df.nunique()

AGE             50
SEXE             2
TDT              4
PAR             67
CHOLESTEROL    222
GAJ              2
ECG              3
FCMAX          119
ANGINE           2
DEPRESSION      53
PENTE            3
CŒUR             2
dtype: int64

In [8]:
#5-Verifier s'il y a des données manquante 
df.isna().sum()

AGE            0
SEXE           0
TDT            0
PAR            0
CHOLESTEROL    0
GAJ            0
ECG            0
FCMAX          0
ANGINE         0
DEPRESSION     0
PENTE          0
CŒUR           0
dtype: int64

In [9]:
#6- Normalisation des variables quantitatives 
var_quant = df.select_dtypes(exclude='object').drop('CŒUR', axis=1).columns
for col in var_quant:
  df[col] = pd.DataFrame(df[col]/df[col].mean())
var_normale = df[var_quant]
var_normale

AGE       PAR  CHOLESTEROL      GAJ     FCMAX  DEPRESSION 
0    0.747511  1.057430     1.453726  0.00000  1.257224     0.000000
1    0.915701  1.208491     0.905435  0.00000  1.140273     1.126933
2    0.691448  0.981899     1.423544  0.00000  0.716325     0.000000
3    0.897014  1.042324     1.076461  0.00000  0.789420     1.690400
4    1.009140  1.132960     0.980887  0.00000  0.891752     0.000000
..        ...       ...          ...      ...       ...          ...
913  0.840950  0.830838     1.327971  0.00000  0.964846     1.352320
914  1.270769  1.087642     0.970827  4.28972  1.030631     3.831574
915  1.065204  0.981899     0.658955  0.00000  0.840586     1.352320
916  1.065204  0.981899     1.187125  0.00000  1.271843     0.000000
917  0.710136  1.042324     0.880284  0.00000  1.264533     0.000000

[918 rows x 6 columns]

In [10]:
#7-Faire le recodage de toutes les variables qualitative
def recod(params):
  return params.astype('category').cat.codes

In [11]:
def recod_global(data):
  for col in data.select_dtypes('object').columns:
    data[col] = recod(data[col])
    return data


In [22]:
recod_global(df)

AGE  SEXE  TDT       PAR  ...  ANGINE  DEPRESSION   PENTE  CŒUR
0    0.747511     1    0  1.057430  ...       0     0.000000      0     0
1    0.915701     0    3  1.208491  ...       0     1.126933      2     1
2    0.691448     1    0  0.981899  ...       0     0.000000      0     0
3    0.897014     0    1  1.042324  ...       1     1.690400      2     1
4    1.009140     1    3  1.132960  ...       0     0.000000      0     0
..        ...   ...  ...       ...  ...     ...          ...    ...   ...
913  0.840950     1    2  0.830838  ...       0     1.352320      2     1
914  1.270769     1    1  1.087642  ...       0     3.831574      2     1
915  1.065204     1    1  0.981899  ...       1     1.352320      2     1
916  1.065204     0    0  0.981899  ...       0     0.000000      2     1
917  0.710136     1    3  1.042324  ...       0     0.000000      0     0

[918 rows x 12 columns]

In [23]:
#8-Separation des données 

Y = df[['CŒUR']]
X = df[['AGE','SEXE','TDT', 'PAR','CHOLESTEROL','GAJ','ECG','FCMAX','ANGINE','DEPRESSION ','PENTE']]
X

AGE  SEXE  TDT       PAR  ...     FCMAX  ANGINE  DEPRESSION   PENTE
0    0.747511     1    0  1.057430  ...  1.257224       0     0.000000      0
1    0.915701     0    3  1.208491  ...  1.140273       0     1.126933      2
2    0.691448     1    0  0.981899  ...  0.716325       0     0.000000      0
3    0.897014     0    1  1.042324  ...  0.789420       1     1.690400      2
4    1.009140     1    3  1.132960  ...  0.891752       0     0.000000      0
..        ...   ...  ...       ...  ...       ...     ...          ...    ...
913  0.840950     1    2  0.830838  ...  0.964846       0     1.352320      2
914  1.270769     1    1  1.087642  ...  1.030631       0     3.831574      2
915  1.065204     1    1  0.981899  ...  0.840586       1     1.352320      2
916  1.065204     0    0  0.981899  ...  1.271843       0     0.000000      2
917  0.710136     1    3  1.042324  ...  1.264533       0     0.000000      0

[918 rows x 11 columns]

In [24]:
#9-Utilisation de la fonction train_test_split du module model_selection de sklearn

from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size=0.2, random_state=1)
print('Train_set :',X_train.shape)
print('test_set :',X_test.shape)

Train_set : (734, 11)
test_set : (184, 11)


In [26]:
#10-Regression logistique 
from sklearn.linear_model import LogisticRegression

In [27]:
logReg = LogisticRegression()
logReg.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [28]:
#11- Affichage de la probabilité d'appartenance à chacune des classes de la variable coeur

logReg.predict_proba(X_test[:5])

array([[0.32777726, 0.67222274],
       [0.17504272, 0.82495728],
       [0.03672641, 0.96327359],
       [0.08969688, 0.91030312],
       [0.23290901, 0.76709099]])

In [30]:
#12- Prediction de la classe d'appartenance de chaque individu de X_test
y_pred = logReg.predict(X_test)
y_pred

array([1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0])

#13- Matrice de confusion, taux de succès, sensibilité et précision du model

In [31]:
# Matrice de confusion
from sklearn.metrics import confusion_matrix
mat_conf = confusion_matrix(y_pred,y_test)
mat_conf

array([[ 66,   8],
       [  8, 102]])

In [32]:
#accuracy_score 
from sklearn.metrics import accuracy_score
acc_score = accuracy_score(y_pred,y_test)
acc_score

0.9130434782608695

In [33]:
#recall score 
from sklearn.metrics import recall_score
rec_score = recall_score(y_pred,y_test)
rec_score

0.9272727272727272

In [34]:
#precision score
from sklearn.metrics import precision_score
prec_score = precision_score(y_pred,y_test)
prec_score

0.9272727272727272